version: "3" 
services: 
 app: 
   container_name: app_Francesco_Rumiz_IN2300010
   build: . 
   command: nodemon --watch /usr/src/app -e js index.js 
   ports: 
     - "5000:5000" 
   volumes: 
     - ./app:/usr/src/app 
     - /usr/src/app/node_modules
   environment:
     - JWT_SECRET=lookandbook_secret
     - MONGO_URL=mongodb://mongosrv:27017/sportapp
   links:
     - "mongo:mongosrv"
 mongo: 
   container_name: mongo_Francesco_Rumiz_IN2300010
   image: mongo 
   volumes: 
     - ./data:/data/db 
     - ./init:/docker-entrypoint-initdb.d
   ports: 
     - '27017:27017' 